### ISSUE TITLE
Missing validation of the data loaded

### ISSUE THREAD

**Issue by righettod** [b4stet/py_aqua#2]
After loading of the JSON content in the **analyze** web handler, the content is not validated like it is performed in the **quiz** web handler:

![image](https://user-images.githubusercontent.com/1573775/94144666-bd5d7680-fe71-11ea-918b-e4bc4deefa8f.png)

Validation expected:

![image](https://user-images.githubusercontent.com/1573775/94144779-df56f900-fe71-11ea-9ebe-aa9dabef7faa.png)

**Comment by b4stet** [comment]
thanks for pointing this out !
